#spring:
#  datasource:
#    url: jdbc:postgresql://auth-db:5432/skilltrack_auth
#    username: '{cipher}589dc3d84e25c6e407abdf9c018c1c78f45812222c1af355c74fbe8125e314d2'
#    password: '{cipher}589dc3d84e25c6e407abdf9c018c1c78f45812222c1af355c74fbe8125e314d2'
#    driver-class-name: org.postgresql.Driver

spring:
  datasource:
    url: jdbc:postgresql://auth-db:5432/${AUTH_DB_NAME}
    username: ${AUTH_DB_USER}
    password: ${AUTH_DB_PASSWORD}
