eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

spring:
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: 1
      retries: 1
      properties:
        retry.backoff.ms: 500
        enable.idempotence: false
        spring.json.type.mapping: event:com.skilltrack.common.event.NotificationEvent
        spring.json.add.type.headers: true
    consumer:
      group-id: notification-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        request.timeout.ms: 60000
        spring.json.trusted.packages: com.skilltrack.common.event
        spring.json.value.default.type: com.skilltrack.common.event.NotificationEvent

logging:
  level:
    com.popov: DEBUG
    org.springframework.cloud.netflix.eureka: INFO
    org.springframework.kafka: INFO
    feign: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/application.log
    max-size: 10MB
    max-history: 7

app:
  notification:
    topic: notification-events
  url:
    base: http://localhost:9090
