spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/skilltrack_notification
    username: '{cipher}589dc3d84e25c6e407abdf9c018c1c78f45812222c1af355c74fbe8125e314d2'
    password: '{cipher}589dc3d84e25c6e407abdf9c018c1c78f45812222c1af355c74fbe8125e314d2'
    driver-class-name: org.postgresql.Driver

#  mail:
#    host: ${MAIL_HOST}
#    port: ${MAIL_PORT}
#    username: ${MAIL_USERNAME}
#    password: ${MAIL_PASSWORD}
#    properties:
#      mail:
#        debug: false
#        transport:
#          protocol: smtp
#        smtp:
#          auth: true
#          starttls:
#            enable: true
