spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: public
    default-schema: public
