messaging:
  exchange: skilltrack.exchange
  routing-keys:
    user-created: user.created
    password-reset: user.password-reset

notification:
  templates:
    verification:
      subject: "SkillTrack - Email Verification"
      content: |
        Hello,
        
        Please verify your email address by entering the verification code below:
        
        CODE: {0}
        
        Enter this code on the verification page to complete your registration.
        
        This code will expire in 7 days.
        
        If you did not create an account, please ignore this email.
        
        Thanks,
        The SkillTrack Team

    password_reset:
      subject: "SkillTrack - Password Reset"
      content: |
        Hello,
        
        You have requested to reset your password. Please use the code below to reset it:
        
        CODE: {0}
        
        This code will expire in 1 day.
        
        If you did not request a password reset, please ignore this email.
        
        Thanks,
        The SkillTrack Team
